export const vr = {
  code: 200,
  msg: 'success',
  data: {
    vinCode: null,
    simNumber: null,
    vehicleType: null,
    licensePlateNumber: null,
    vehicleName: null,
    owner: null,
    ownerMobile: null,
    driver: null,
    driverMobile: null,
    totalMileage: 8893.0,
    totalRunTime: 0.0,
    totalCost: 3720.2,
    serviceTime: 230.89,
    remainEnergy: 63.0,
    time: '2022-12-30',
    longitude: 120.50253,
    latitude: 31.503286,
    vehicleSpeed: 0.0,
    vehStatus: 3,
    vehStatusText: '充电中',
  },
};
